
run : com/github/MickiFoerster/protobuf/SimpleMain.class
	java -cp .:protobuf-java-3.10.0.jar com.github.MickiFoerster.protobuf.SimpleMain


com/github/MickiFoerster/protobuf/SimpleMain.class : com.github.MickiFoerster.protobuf/SimpleMain.java
	javac -cp .:protobuf-java-3.10.0.jar com.github.MickiFoerster.protobuf/SimpleMain.java 
	javac -d . -cp .:protobuf-java-3.10.0.jar com.github.MickiFoerster.protobuf/SimpleMain.java 


.PHONY: run